# Generated by Django 6.0.3 on 2026-03-31 09:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('watched_type', models.CharField(choices=[('full', 'Полный матч'), ('highlights', 'Только голы'), ('partial', 'Фрагменты')], default='full', max_length=20, verbose_name='Тип просмотра')),
                ('attended_stadium', models.BooleanField(default=False, verbose_name='Посещал стадион')),
            ],
            options={
                'verbose_name': 'Контекст оценки',
                'verbose_name_plural': 'Контексты оценок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('started', 'Начато'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('abandoned', 'Заброшено')], default='started', max_length=20, verbose_name='Статус')),
                ('completed_steps', models.JSONField(default=list, verbose_name='Завершённые шаги')),
                ('current_step', models.CharField(default='context', max_length=50, verbose_name='Текущий шаг')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
            ],
            options={
                'verbose_name': 'Сессия оценки',
                'verbose_name_plural': 'Сессии оценок',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entertainment', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Зрелищность')),
                ('tension', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Напряжение')),
                ('turning_point', models.BooleanField(default=False, verbose_name='Переломный момент')),
                ('fairness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Справедливость')),
            ],
            options={
                'verbose_name': 'Оценка матча',
                'verbose_name_plural': 'Оценки матчей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contribution', models.IntegerField(help_text='Вклад в игру (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Вклад')),
                ('risk', models.IntegerField(help_text='Риск/ошибки (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Риск')),
                ('potential', models.IntegerField(help_text='Потенциал (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Потенциал')),
            ],
            options={
                'verbose_name': 'Оценка игрока',
                'verbose_name_plural': 'Оценки игроков',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefereeEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influence_score', models.IntegerField(help_text='Влияние на матч (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Влияние на матч')),
                ('decision_quality', models.IntegerField(help_text='Качество решений (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Качество решений')),
            ],
            options={
                'verbose_name': 'Оценка судейства',
                'verbose_name_plural': 'Оценки судейства',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tactics', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Тактика')),
                ('effort', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Самоотдача')),
                ('organization', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Организация')),
                ('mentality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Менталитет')),
            ],
            options={
                'verbose_name': 'Оценка команды',
                'verbose_name_plural': 'Оценки команд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tactics', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Тактика')),
                ('substitutions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Замены')),
                ('game_management', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Управление')),
                ('impact', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Влияние')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_evaluations', to='coaches.coach', verbose_name='Тренер')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_evaluations', to='matches.match', verbose_name='Матч')),
            ],
            options={
                'verbose_name': 'Оценка тренера',
                'verbose_name_plural': 'Оценки тренеров',
                'ordering': ['-created_at'],
            },
        ),
    ]
