# Generated by Django 6.0.3 on 2026-03-31 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coachevaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='contextevaluation',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_evaluations', to='matches.match', verbose_name='Матч'),
        ),
        migrations.AddField(
            model_name='contextevaluation',
            name='supported_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supported_by_users', to='teams.team', verbose_name='Поддерживаемая команда'),
        ),
        migrations.AddField(
            model_name='contextevaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions', to='matches.match', verbose_name='Матч'),
        ),
        migrations.AddField(
            model_name='evaluationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='matchevaluation',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_evaluations', to='matches.match', verbose_name='Матч'),
        ),
        migrations.AddField(
            model_name='matchevaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_evaluations', to='matches.match', verbose_name='Матч'),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_evaluations', to='players.player', verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='playerevaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='refereeevaluation',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_evaluations', to='matches.match', verbose_name='Матч'),
        ),
        migrations.AddField(
            model_name='refereeevaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='teamevaluation',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_evaluations', to='matches.match', verbose_name='Матч'),
        ),
        migrations.AddField(
            model_name='teamevaluation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_evaluations', to='teams.team', verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='teamevaluation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='coachevaluation',
            constraint=models.UniqueConstraint(fields=('user', 'match', 'coach'), name='unique_coach_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='contextevaluation',
            constraint=models.UniqueConstraint(fields=('user', 'match'), name='unique_context_evaluation'),
        ),
        migrations.AddIndex(
            model_name='evaluationsession',
            index=models.Index(fields=['user', 'status'], name='evaluations_user_id_ce40c1_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationsession',
            index=models.Index(fields=['match', 'status'], name='evaluations_match_i_1a2959_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationsession',
            constraint=models.UniqueConstraint(fields=('user', 'match'), name='unique_evaluation_session'),
        ),
        migrations.AddConstraint(
            model_name='matchevaluation',
            constraint=models.UniqueConstraint(fields=('user', 'match'), name='unique_match_evaluation'),
        ),
        migrations.AddIndex(
            model_name='playerevaluation',
            index=models.Index(fields=['match', 'player'], name='evaluations_match_i_e27e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='playerevaluation',
            index=models.Index(fields=['player', 'match'], name='evaluations_player__2a0e48_idx'),
        ),
        migrations.AddIndex(
            model_name='playerevaluation',
            index=models.Index(fields=['user', 'match'], name='evaluations_user_id_7a9f74_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerevaluation',
            constraint=models.UniqueConstraint(fields=('user', 'match', 'player'), name='unique_player_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='refereeevaluation',
            constraint=models.UniqueConstraint(fields=('user', 'match'), name='unique_referee_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='teamevaluation',
            constraint=models.UniqueConstraint(fields=('user', 'match', 'team'), name='unique_team_evaluation'),
        ),
    ]
