# Generated by Django 6.0.3 on 2026-03-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchevaluation',
            name='evaluations_match_us_11111_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerevaluation',
            name='evaluations_match_pla_12345_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerevaluation',
            name='evaluations_user_ma_67890_idx',
        ),
    ]
