# Generated by Django 6.0.3 on 2026-08-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес завершения'),
        ),
    ]
