# Generated by Django 6.0.3 on 2026-03-18 11:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_remove_matchevaluation_evaluations_match_us_11111_idx_and_more'),
        ('matches', '0007_remove_match_matches_match_league_sea_12345_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextevaluation',
            name='watched_type',
            field=models.CharField(choices=[('full', 'Полный матч'), ('highlights', 'Только голы'), ('partial', 'Фрагменты')], default='full', max_length=20),
        ),
        migrations.CreateModel(
            name='EvaluationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('started', 'Начато'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('abandoned', 'Заброшено')], default='started', max_length=20)),
                ('completed_steps', models.JSONField(default=list)),
                ('current_step', models.CharField(default='context', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='evaluations_user_id_ce40c1_idx'), models.Index(fields=['match', 'status'], name='evaluations_match_i_1a2959_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'match'), name='unique_evaluation_session')],
            },
        ),
    ]
