# Generated by Django 6.0.8 on 2026-09-25 06:54

from django.db import migrations, models
from django.db.models import F


def mark_existing_settled(apps, schema_editor):
    # По старым сессиям trust уже начислен при завершении — повторно не считаем.
    EvaluationSession = apps.get_model("evaluations", "EvaluationSession")
    EvaluationSession.objects.filter(status="completed").update(trust_settled_at=F("completed_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_evaluationsession_mode_default_quick'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsession',
            name='trust_settled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trust score учтён'),
        ),
        migrations.RunPython(mark_existing_settled, migrations.RunPython.noop),
    ]
