# Generated by Django 6.0.8 on 2026-09-26 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_security_integrity_fields'),
        ('events', '0006_matchevent_sportmonks_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevaluation',
            name='turning_point_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turning_point_votes', to='events.matchevent', verbose_name='Переломное событие'),
        ),
        migrations.AddField(
            model_name='matchevaluation',
            name='turning_point_kind',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Тип перелома'),
        ),
    ]
