# Generated by Django 6.0.8 on 2026-09-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_matchevaluation_turning_point_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsession',
            name='pending_xp',
            field=models.FloatField(default=0, verbose_name='Накопленный XP'),
        ),
    ]
