# Generated by Django 6.0.3 on 2026-03-31 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0001_initial'),
        ('core', '0001_initial'),
        ('leagues', '0001_initial'),
        ('referees', '0001_initial'),
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('live', 'Идёт'), ('finished', 'Завершён')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('home_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Счёт дома')),
                ('away_score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Счёт гостей')),
                ('has_lineup', models.BooleanField(default=False, verbose_name='Есть состав')),
                ('voting_open_until', models.DateTimeField(verbose_name='Голосование до')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
                ('away_coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_coached_matches', to='coaches.coach', verbose_name='Гостевой тренер')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team', verbose_name='Гостевая команда')),
                ('home_coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_coached_matches', to='coaches.coach', verbose_name='Домашний тренер')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team', verbose_name='Домашняя команда')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league', verbose_name='Лига')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referees.referee', verbose_name='Судья')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season', verbose_name='Сезон')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stadium', verbose_name='Стадион')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['status', 'start_time'], name='matches_mat_status_043f73_idx'), models.Index(fields=['league', 'season', 'start_time'], name='matches_mat_league__250659_idx')],
            },
        ),
    ]
