# Generated by Django 6.0.3 on 2026-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0001_initial'),
        ('core', '0001_initial'),
        ('leagues', '0001_initial'),
        ('matches', '0001_initial'),
        ('referees', '0001_initial'),
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'end_time'], name='matches_mat_status_2e1034_idx'),
        ),
    ]
