# Generated by Django 6.0.3 on 2026-03-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_away_score_alter_match_home_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='has_lineup',
            field=models.BooleanField(default=False),
        ),
    ]
