# Generated by Django 6.0.3 on 2026-03-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='matches_match_league_sea_12345_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='matches_match_status__67890_idx',
        ),
    ]
