# Generated by Django 6.0.3 on 2026-08-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_matchteamstatistics_matchplayerstatistics'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='matchplayerstatistics',
            new_name='matches_mat_team_id_bcf70f_idx',
            old_name='matches_mat_team_id_5f2e91_idx',
        ),
    ]
