# Generated by Django 6.0.8 on 2026-10-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_alter_match_manual_override_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='live_counts_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Период считается с минуты'),
        ),
        migrations.AddField(
            model_name='match',
            name='live_period_started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало текущего периода'),
        ),
        migrations.AddField(
            model_name='match',
            name='live_state',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Состояние live'),
        ),
        migrations.AddField(
            model_name='match',
            name='live_ticking',
            field=models.BooleanField(default=False, verbose_name='Часы идут'),
        ),
    ]
