# Generated by Django 6.0.3 on 2026-03-31 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='Логотип')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='URL логотипа')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season', verbose_name='Сезон')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Команда в сезоне',
                'verbose_name_plural': 'Команды в сезонах',
                'constraints': [models.UniqueConstraint(fields=('team', 'season'), name='unique_team_season')],
            },
        ),
        migrations.CreateModel(
            name='TeamSeasonStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('played', models.PositiveIntegerField(default=0, verbose_name='Игры')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='Победы')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='Ничьи')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='Поражения')),
                ('goals_scored', models.PositiveIntegerField(default=0, verbose_name='Забитые голы')),
                ('goals_conceded', models.PositiveIntegerField(default=0, verbose_name='Пропущенные голы')),
                ('goal_diff', models.IntegerField(default=0, verbose_name='Разница мячей')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиция')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season', verbose_name='Сезон')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Статистика команды в сезоне',
                'verbose_name_plural': 'Статистика команд в сезоне',
                'ordering': ['-points', '-goal_diff', '-goals_scored'],
                'indexes': [models.Index(fields=['season', '-points', '-goal_diff'], name='team_season_stats_season_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'season'), name='unique_team_season_stats')],
            },
        ),
    ]
