# Generated by Django 6.0.3 on 2026-08-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rivals',
            field=models.ManyToManyField(blank=True, help_text='Команды, матчи с которыми считаются дерби для бейджа «Дерби-эксперт».', to='teams.team', verbose_name='Принципиальные соперники'),
        ),
    ]
