# Generated by Django 6.0.3 on 2026-03-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
