# Generated by Django 6.0.3 on 2026-03-20 14:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0003_alter_season_options_alter_season_external_id_and_more'),
        ('teams', '0005_alter_team_options_alter_teamseason_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeasonStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('played', models.PositiveIntegerField(default=0, verbose_name='Игры')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='Победы')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='Ничьи')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='Поражения')),
                ('goals_scored', models.PositiveIntegerField(default=0, verbose_name='Забитые голы')),
                ('goals_conceded', models.PositiveIntegerField(default=0, verbose_name='Пропущенные голы')),
                ('goal_diff', models.IntegerField(default=0, verbose_name='Разница мячей')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиция')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.season', verbose_name='Сезон')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Статистика команды в сезоне',
                'verbose_name_plural': 'Статистика команд в сезоне',
                'ordering': ['-points', '-goal_diff', '-goals_scored'],
                'indexes': [models.Index(fields=['season', '-points', '-goal_diff'], name='team_season_stats_season_idx')],
                'constraints': [models.UniqueConstraint(fields=('team', 'season'), name='unique_team_season_stats')],
            },
        ),
    ]
