# Generated by Django 6.0.8 on 2026-10-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_alter_team_logo_alter_team_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='squad_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Состав сверен'),
        ),
    ]
