# Generated by Django 6.0.8 on 2026-10-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_current_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='brand_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет клуба'),
        ),
    ]
