# Generated by Django 6.0.3 on 2026-03-19 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_evaluation_streak_user_last_evaluation_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-trust_score', '-total_evaluations'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-awarded_at'], 'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='userxp',
            options={'verbose_name': 'Опыт пользователя', 'verbose_name_plural': 'Опыт пользователей'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='evaluation_streak',
            field=models.IntegerField(default=0, verbose_name='Серия оценок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицирован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_evaluation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Последняя оценка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating_power',
            field=models.FloatField(default=1.0, verbose_name='Сила рейтинга'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_evaluations',
            field=models.IntegerField(default=0, verbose_name='Всего оценок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trust_score',
            field=models.FloatField(default=1.0, verbose_name='Оценка доверия'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge_type',
            field=models.CharField(choices=[('first_evaluation', 'Первая оценка'), ('active_fan_10', 'Активный фанат (10 матчей)'), ('active_fan_50', 'Хардкор фанат (50 матчей)'), ('accurate_analyst', 'Точный аналитик'), ('bias_free', 'Без предвзятости'), ('early_bird', 'Ранняя пташка'), ('streak_7', 'Неделя подряд'), ('streak_30', 'Месяц подряд')], max_length=50, verbose_name='Тип достижения'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userxp',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='userxp',
            name='total_xp',
            field=models.IntegerField(default=0, verbose_name='Всего опыта'),
        ),
        migrations.AlterField(
            model_name='userxp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
