# Generated by Django 6.0.3 on 2026-04-01 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_notification_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification_settings',
        ),
    ]
