# Generated by Django 6.0.3 on 2026-04-01
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_notification_settings',
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name='Настройки уведомлений',
                db_column='notification_settings'
            ),
        ),
    ]