# Generated by Django 6.0.3 on 2026-04-02 11:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_notification_settings_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Токен верификации'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания токена'),
            preserve_default=False,
        ),
    ]
