# Generated by Django 6.0.3 on 2026-08-14 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_matches_mat_status_2e1034_idx'),
        ('users', '0005_user_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP при регистрации'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_user_agent',
            field=models.TextField(blank=True, verbose_name='User-Agent при регистрации'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge_type',
            field=models.CharField(choices=[('first_evaluation', 'Первая оценка'), ('active_fan_10', 'Активный фанат'), ('active_fan_50', 'Хардкор фанат'), ('active_fan_150', 'Легенда трибун'), ('streak_7', 'Неделя подряд'), ('streak_30', 'Месяц подряд'), ('streak_100', 'Железная дисциплина'), ('accurate_analyst', 'Точный аналитик'), ('foresight', 'Провидец'), ('bias_free', 'Без предвзятости'), ('early_bird', 'Ранняя пташка'), ('judge_of_judges', 'Судья судей'), ('polyglot', 'Полиглот лиги'), ('founder', 'Первопроходец')], max_length=50, verbose_name='Тип достижения'),
        ),
        migrations.CreateModel(
            name='SuspiciousActivityFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('fast_wizard', 'Слишком быстрое заполнение вайзарда оценки'), ('ip_cluster', 'Кластер аккаунтов с одного IP'), ('extreme_bias', 'Экстремальная историческая предвзятость'), ('manual', 'Отмечено вручную модератором')], max_length=30, verbose_name='Источник сигнала')),
                ('score', models.FloatField(default=0.0, help_text='0.0 (незначительно) .. 1.0 (крайне подозрительно)', verbose_name='Скор подозрительности')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Детали')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('confirmed', 'Подтверждено — накрутка'), ('dismissed', 'Отклонено — ложное срабатывание')], default='pending', max_length=20, verbose_name='Статус')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_activity_flags', to='matches.match', verbose_name='Матч')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suspicious_flags', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_activity_flags', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сигнал подозрительной активности',
                'verbose_name_plural': 'Сигналы подозрительной активности',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='users_suspi_status_78eded_idx'), models.Index(fields=['user', '-created_at'], name='users_suspi_user_id_ec7ca9_idx')],
            },
        ),
    ]
