# Generated by Django 6.0.3 on 2026-08-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_registration_ip_user_registration_user_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='badge_type',
            field=models.CharField(choices=[('first_evaluation', 'Первая оценка'), ('active_fan_10', 'Активный фанат'), ('active_fan_50', 'Хардкор фанат'), ('active_fan_150', 'Легенда трибун'), ('streak_7', 'Неделя подряд'), ('streak_30', 'Месяц подряд'), ('streak_100', 'Железная дисциплина'), ('accurate_analyst', 'Точный аналитик'), ('foresight', 'Провидец'), ('bias_free', 'Без предвзятости'), ('early_bird', 'Ранняя пташка'), ('judge_of_judges', 'Судья судей'), ('polyglot', 'Полиглот лиги'), ('derby_hunter', 'Дерби-эксперт'), ('monthly_champion', 'Чемпион месяца'), ('founder', 'Первопроходец')], max_length=50, verbose_name='Тип достижения'),
        ),
    ]
