# Generated by Django 6.0.3 on 2026-08-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_suspiciousactivityflag_vote_spike_entity_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='suspiciousactivityflag',
            new_name='users_suspi_content_5fc2c2_idx',
            old_name='users_suspi_content_9e1f3a_idx',
        ),
    ]
