# Generated by Django 6.0.3 on 2026-08-23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_users_suspi_content_9e1f3a_idx_users_suspi_content_5fc2c2_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiFraudThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Ключ порога')),
                ('value', models.FloatField(verbose_name='Текущее действующее значение')),
                ('default_value', models.FloatField(verbose_name='Значение по умолчанию (старт калибровки)')),
                ('min_value', models.FloatField(verbose_name='Нижняя граница калибровки')),
                ('max_value', models.FloatField(verbose_name='Верхняя граница калибровки')),
                ('last_note', models.CharField(blank=True, help_text='Заполняется автоматически задачей пересчёта — для прозрачности в admin.', max_length=255, verbose_name='Причина последнего изменения')),
            ],
            options={
                'verbose_name': 'Порог антифрода',
                'verbose_name_plural': 'Пороги антифрода (самокалибровка)',
                'ordering': ['key'],
            },
        ),
    ]
