# Generated by Django 6.0.8 on 2026-09-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_userbadge_is_stale_and_stale_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='is_stale',
            field=models.BooleanField(default=False, help_text='Только для статусных достижений — показатель упал ниже порога после получения бейджа.', verbose_name='Утратил актуальность'),
        ),
    ]
