# Generated by Django 6.0.8 on 2026-09-25 06:54

from django.db import migrations, models


def _canonical(email):
    email = (email or "").strip().lower()
    if "@" not in email:
        return email
    local, domain = email.rsplit("@", 1)
    local = local.split("+", 1)[0]
    if domain in ("gmail.com", "googlemail.com"):
        local = local.replace(".", "")
        domain = "gmail.com"
    return f"{local}@{domain}"


def fill_email_canonical(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.only("id", "email").iterator():
        User.objects.filter(pk=user.pk).update(email_canonical=_canonical(user.email))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_suspiciousactivityflag_coach_stats_divergence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_canonical',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=254, verbose_name='Email (нормализованный)'),
        ),
        migrations.AddField(
            model_name='userxp',
            name='xp_remainder',
            field=models.FloatField(default=0.0, verbose_name='Дробный остаток XP'),
        ),
        migrations.RunPython(fill_email_canonical, migrations.RunPython.noop),
    ]
