# Generated by Django 6.0.8 on 2026-09-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_security_integrity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbadge',
            name='badge_type',
            field=models.CharField(choices=[('first_evaluation', 'Первая оценка'), ('active_fan_10', 'Активный фанат'), ('active_fan_50', 'Хардкор фанат'), ('active_fan_150', 'Легенда трибун'), ('streak_7', 'Верный трибунам'), ('streak_30', 'Сезонный болельщик'), ('streak_100', 'Железная дисциплина'), ('accurate_analyst', 'Точный аналитик'), ('foresight', 'Провидец'), ('bias_free', 'Без предвзятости'), ('early_bird', 'Ранняя пташка'), ('judge_of_judges', 'Судья судей'), ('polyglot', 'Полиглот лиги'), ('first_prediction', 'Первый прогноз'), ('prediction_streak_7', 'Аналитик недели'), ('prediction_streak_30', 'Штатный прогнозист'), ('prediction_streak_100', 'Оракул трибун'), ('derby_hunter', 'Дерби-эксперт'), ('monthly_champion', 'Чемпион месяца'), ('founder', 'Первопроходец'), ('coach_expert', 'Тренерский эксперт'), ('both_sides', 'Обе стороны'), ('full_season', 'Полный сезон'), ('stable_hand', 'Стабильная рука'), ('derby_prophet', 'Дерби-пророк'), ('against_the_tide', 'Против течения'), ('perfect_tour', 'Идеальный тур'), ('streak_250', 'Живая легенда трибун'), ('prediction_streak_200', 'Абсолютный оракул'), ('season_completionist', 'Стоглазый'), ('max_trust', 'Максимальное доверие'), ('day_streak_7', 'Неделя с DOPX'), ('day_streak_30', 'Месяц на трибуне'), ('day_streak_100', 'Сто дней с командой'), ('day_streak_365', 'Год без пропусков'), ('came_with_friend', 'Пришёл с другом'), ('recruiter_1', 'Позвал на трибуну'), ('recruiter_5', 'Заводила сектора'), ('recruiter_20', 'Капо фанатов'), ('season_pass_10', 'Болельщик сезона'), ('season_pass_20', 'Опора трибун'), ('season_pass_30', 'Легенда сезона')], max_length=50, verbose_name='Тип достижения'),
        ),
    ]
