# Generated by Django 6.0.8 on 2026-10-03 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_experttake_review_note'),
        ('users', '0026_engagement_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_name', models.CharField(blank=True, max_length=150, verbose_name='Ник или название на момент жалобы')),
                ('reason', models.CharField(choices=[('name', 'Оскорбительный ник или название'), ('avatar', 'Неприемлемый аватар'), ('bio', 'Оскорбления в описании'), ('spam', 'Спам или реклама'), ('impersonation', 'Выдаёт себя за другого'), ('other', 'Другое')], max_length=20, verbose_name='Причина')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('resolved', 'Приняты меры'), ('rejected', 'Отклонена')], db_index=True, default='new', max_length=10, verbose_name='Статус')),
                ('action', models.CharField(blank=True, max_length=30, verbose_name='Принятые меры')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда разобрано')),
                ('friend_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='engagement.friendleague', verbose_name='Лига друзей')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто разобрал')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_sent', to=settings.AUTH_USER_MODEL, verbose_name='Кто пожаловался')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='На кого')),
            ],
            options={
                'verbose_name': 'Жалоба пользователя',
                'verbose_name_plural': 'Жалобы пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
