# Generated by Django 6.0.8 on 2026-10-03 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Активированные аккаунты с настоящей почтой — почта подтверждена; все настоящие адреса закрепляем."""
    User = apps.get_model("users", "User")
    UsedEmail = apps.get_model("users", "UsedEmail")
    real = User.objects.exclude(email__iendswith="@telegram.invalid").exclude(email="")
    for user in real.filter(is_verified=True).only("pk", "date_joined").iterator():
        User.objects.filter(pk=user.pk).update(email_verified_at=user.date_joined)
    UsedEmail.objects.bulk_create(
        [UsedEmail(user_id=u.pk, email_canonical=u.email_canonical or u.email.lower())
         for u in real.filter(is_verified=True).only("pk", "email", "email_canonical").iterator()],
        ignore_conflicts=True, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_user_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Почта подтверждена'),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Новая почта (ждёт подтверждения)'),
        ),
        migrations.CreateModel(
            name='UsedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_canonical', models.CharField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Использованная почта',
                'verbose_name_plural': 'Использованные почты',
                'constraints': [models.UniqueConstraint(fields=('user', 'email_canonical'), name='used_email_unique')],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
