# Generated by Django 6.0.3 on 2026-03-31 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minute', models.PositiveSmallIntegerField(help_text='Минута события')),
                ('added_time', models.PositiveSmallIntegerField(default=0, help_text='Добавленное время (+1, +2...)')),
                ('event_type', models.CharField(choices=[('goal', 'Гол'), ('yellow_card', 'Жёлтая карточка'), ('red_card', 'Красная карточка'), ('substitution', 'Замена'), ('penalty', 'Пенальти'), ('own_goal', 'Автогол'), ('var_check', 'VAR проверка')], max_length=20)),
                ('team_side', models.CharField(choices=[('home', 'Домашние'), ('away', 'Гостевые')], max_length=4)),
                ('score_after', models.CharField(blank=True, help_text='Например: 2-1', max_length=5)),
                ('card_reason', models.CharField(blank=True, choices=[('unsporting', 'Неспортивное поведение'), ('dissent', 'Диссидентство'), ('persistent_fouling', 'Систематические нарушения'), ('delaying_restart', 'Задержка возобновления'), ('entering_field', 'Незаконный выход на поле'), ('other', 'Другое')], max_length=30, null=True)),
                ('var_decision', models.CharField(blank=True, help_text='Решение после VAR', max_length=50)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Сырые данные из API')),
                ('assist_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists', to='players.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='players.player')),
                ('player_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutions_out', to='players.player')),
            ],
            options={
                'verbose_name': 'Событие матча',
                'verbose_name_plural': 'События матча',
                'ordering': ['minute', 'added_time', 'id'],
            },
        ),
    ]
