# Generated by Django 6.0.3 on 2026-03-20 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('players', '0002_player_external_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchevent',
            options={'ordering': ['minute', 'added_time', 'id'], 'verbose_name': 'Событие матча', 'verbose_name_plural': 'События матча'},
        ),
        migrations.RemoveField(
            model_name='matchevent',
            name='external_id',
        ),
        migrations.AddField(
            model_name='matchevent',
            name='added_time',
            field=models.PositiveSmallIntegerField(default=0, help_text='Добавленное время (+1, +2...)'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='assist_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists', to='players.player'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='card_reason',
            field=models.CharField(blank=True, choices=[('unsporting', 'Неспортивное поведение'), ('dissent', 'Диссидентство'), ('persistent_fouling', 'Систематические нарушения'), ('delaying_restart', 'Задержка возобновления'), ('entering_field', 'Незаконный выход на поле'), ('other', 'Другое')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Сырые данные из API для отладки'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='player_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutions_out', to='players.player'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='score_after',
            field=models.CharField(blank=True, help_text='Например: 2-1', max_length=5),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='var_decision',
            field=models.CharField(blank=True, help_text='Решение после VAR: гол отменён, пенальти подтверждён...', max_length=50),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Гол'), ('yellow_card', 'Жёлтая карточка'), ('red_card', 'Красная карточка'), ('substitution', 'Замена'), ('penalty', 'Пенальти'), ('own_goal', 'Автогол'), ('var_check', 'VAR проверка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='minute',
            field=models.PositiveSmallIntegerField(help_text='Минута события'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='players.player'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='team_side',
            field=models.CharField(choices=[('home', 'Домашние'), ('away', 'Гостевые')], max_length=4),
        ),
    ]
