# Generated by Django 6.0.3 on 2026-04-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='score_after',
            field=models.CharField(blank=True, help_text='Например: 2-1', max_length=5, null=True),
        ),
    ]
