# Generated by Django 6.0.3 on 2026-03-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_matchevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Сырые данные из API'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='var_decision',
            field=models.CharField(blank=True, help_text='Решение после VAR', max_length=50),
        ),
    ]
