# Generated by Django 6.0.3 on 2026-08-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round_squad', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roundbestxislot',
            new_name='round_squad_content_a5c212_idx',
            old_name='round_squa_content_2f6a41_idx',
        ),
    ]
