# Generated by Django 6.0.8 on 2026-09-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round_squad', '0003_rank_change_and_position_ranking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='roundpositionranking',
            new_name='round_squad_round_b_1f5063_idx',
            old_name='round_squad_round_b_9e1a53_idx',
        ),
        migrations.RenameIndex(
            model_name='roundpositionranking',
            new_name='round_squad_content_f39b38_idx',
            old_name='round_squad_content_9f2b64_idx',
        ),
    ]
