# Generated by Django 6.0.8 on 2026-09-27 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_platformsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MourningMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Включён')),
                ('message', models.CharField(default='День общенационального траура', max_length=255, verbose_name='Текст плашки')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Пусто — сразу', null=True, verbose_name='Начало')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Пусто — до ручного выключения', null=True, verbose_name='Окончание')),
                ('grayscale', models.BooleanField(default=True, verbose_name='Монохромный сайт')),
                ('hide_ads', models.BooleanField(default=True, verbose_name='Скрыть рекламу и баннеры')),
                ('mute_push', models.BooleanField(default=True, verbose_name='Приглушить развлекательные push')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Режим траура',
                'verbose_name_plural': 'Режим траура',
            },
        ),
    ]
