# Generated by Django 6.0.3 on 2026-08-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_name',
            field=models.CharField(choices=[('page_view', 'Просмотр страницы'), ('user_registered', 'Регистрация'), ('user_login', 'Вход'), ('wizard_started', 'Начало оценки матча'), ('wizard_step_completed', 'Завершён шаг оценки'), ('wizard_abandoned', 'Оценка брошена'), ('evaluation_completed', 'Оценка матча завершена'), ('share_card_viewed', 'Просмотр шер-карточки'), ('share_clicked', "Клик 'Поделиться'"), ('profile_viewed', 'Просмотр публичного профиля'), ('leaderboard_viewed', 'Просмотр лидерборда'), ('prediction_made', 'Прогноз на матч сделан'), ('widget_embed_viewed', 'Открытие embed-виджета'), ('partner_referral_visit', 'Переход по партнёрской ссылке'), ('banner_impression', 'Показ баннера'), ('banner_click', 'Клик по баннеру'), ('partner_feed_accessed', 'Запрос партнёрского контент-фида')], db_index=True, max_length=50, verbose_name='Событие'),
        ),
    ]
