# Generated by Django 6.0.8 on 2026-10-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analyticsevent_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='День')),
                ('event_name', models.CharField(choices=[('page_view', 'Просмотр страницы'), ('user_registered', 'Регистрация'), ('user_login', 'Вход'), ('wizard_started', 'Начало оценки матча'), ('wizard_step_completed', 'Завершён шаг оценки'), ('wizard_abandoned', 'Оценка брошена'), ('evaluation_completed', 'Оценка матча завершена'), ('share_card_viewed', 'Просмотр шер-карточки'), ('share_clicked', "Клик 'Поделиться'"), ('profile_viewed', 'Просмотр публичного профиля'), ('leaderboard_viewed', 'Просмотр лидерборда'), ('prediction_made', 'Прогноз на матч сделан'), ('widget_embed_viewed', 'Открытие embed-виджета'), ('partner_referral_visit', 'Переход по партнёрской ссылке'), ('banner_impression', 'Показ баннера'), ('banner_click', 'Клик по баннеру'), ('partner_feed_accessed', 'Запрос партнёрского контент-фида')], max_length=50, verbose_name='Событие')),
                ('events', models.PositiveIntegerField(default=0, verbose_name='Событий')),
                ('visitors', models.PositiveIntegerField(default=0, verbose_name='Уникальных визитов')),
                ('users', models.PositiveIntegerField(default=0, verbose_name='Пользователей')),
            ],
            options={
                'verbose_name': 'Итоги дня (аналитика)',
                'verbose_name_plural': 'Итоги дней (аналитика)',
                'ordering': ['-date', 'event_name'],
                'constraints': [models.UniqueConstraint(fields=('date', 'event_name'), name='analytics_daily_unique')],
            },
        ),
    ]
