# Generated by Django 6.0.3 on 2026-03-31 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=20, verbose_name='Год')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='leagues.league', verbose_name='Лига')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('league', 'year'), name='unique_league_season')],
            },
        ),
    ]
