# Generated by Django 6.0.3 on 2026-03-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_alter_league_options_alter_league_country_and_more'),
        ('seasons', '0002_season_external_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-year'], 'verbose_name': 'Сезон', 'verbose_name_plural': 'Сезоны'},
        ),
        migrations.AlterField(
            model_name='season',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='season',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='season',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='leagues.league', verbose_name='Лига'),
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.CharField(max_length=20, verbose_name='Год'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('league', 'year'), name='unique_league_season'),
        ),
    ]
