# Generated by Django 6.0.3 on 2026-08-21 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_generic_age_disclaimer_help_text'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banner',
            new_name='partners_ba_zone_768a7b_idx',
            old_name='partners_ba_zone_ac_idx',
        ),
    ]
