# Generated by Django 6.0.8 on 2026-09-28 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_rename_partners_ba_zone_ac_idx_partners_ba_zone_768a7b_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AddField(
            model_name='banner',
            name='advertiser',
            field=models.CharField(blank=True, help_text='Показывается в пометке «Реклама · …». Пусто — название партнёра', max_length=120, verbose_name='Рекламодатель'),
        ),
        migrations.AddField(
            model_name='banner',
            name='audience',
            field=models.CharField(choices=[('all', 'Все посетители'), ('guests', 'Только гости'), ('users', 'Только вошедшие')], default='all', max_length=10, verbose_name='Аудитория'),
        ),
        migrations.AddField(
            model_name='banner',
            name='body',
            field=models.CharField(blank=True, max_length=140, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_label',
            field=models.CharField(blank=True, default='Подробнее', max_length=24, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='banner',
            name='daily_cap_per_visitor',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 — без ограничения', verbose_name='Показов одному человеку в день'),
        ),
        migrations.AddField(
            model_name='banner',
            name='format',
            field=models.CharField(choices=[('image', 'Картинка'), ('native', 'Карточка (логотип, текст, кнопка)')], default='image', max_length=10, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='banner',
            name='headline',
            field=models.CharField(blank=True, max_length=70, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Необязательно. Без неё на телефоне покажется картинка для компьютера', upload_to='banners/%Y/%m/', verbose_name='Картинка для телефона'),
        ),
        migrations.AddField(
            model_name='banner',
            name='logo',
            field=models.ImageField(blank=True, upload_to='banners/logos/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='banner',
            name='max_clicks',
            field=models.PositiveIntegerField(blank=True, help_text='Пусто — без лимита', null=True, verbose_name='Лимит кликов'),
        ),
        migrations.AddField(
            model_name='banner',
            name='max_impressions',
            field=models.PositiveIntegerField(blank=True, help_text='Пусто — без лимита', null=True, verbose_name='Лимит показов'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banners/%Y/%m/', verbose_name='Картинка для компьютера'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Включён'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Пусто — собственное промо DOPX', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='partners.partner', verbose_name='Партнёр'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Если в зоне несколько баннеров, вес 3 показывается втрое чаще, чем вес 1', verbose_name='Вес в ротации'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='requires_age_disclaimer',
            field=models.BooleanField(default=False, help_text='Для букмекеров, алкоголя, табака и другого контента 18+', verbose_name='Пометка 18+'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text='Видно только в управлении и как alt картинки', max_length=150, verbose_name='Внутреннее название'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='zone',
            field=models.CharField(choices=[('home_hero', 'Главная — верх'), ('sidebar', 'Главная — правая колонка'), ('match_detail', 'Страница матча'), ('leaderboard', 'Рейтинги пользователей и игроков')], db_index=True, max_length=20, verbose_name='Зона показа'),
        ),
        migrations.CreateModel(
            name='BannerDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name='Показы')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Клики')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='partners.banner')),
            ],
            options={
                'verbose_name': 'Статистика баннера за день',
                'verbose_name_plural': 'Статистика баннеров по дням',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('banner', 'date'), name='unique_banner_daily_stat')],
            },
        ),
    ]
