# Generated by Django 6.0.3 on 2026-03-31 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0001_initial'),
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachMatchAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avg_tactics', models.FloatField(default=0.0, verbose_name='Средняя тактика')),
                ('avg_substitutions', models.FloatField(default=0.0, verbose_name='Средние замены')),
                ('avg_management', models.FloatField(default=0.0, verbose_name='Среднее управление')),
                ('avg_impact', models.FloatField(default=0.0, verbose_name='Среднее влияние')),
                ('total_votes', models.IntegerField(default=0, verbose_name='Всего голосов')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_aggregates', to='coaches.coach', verbose_name='Тренер')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_aggregates', to='matches.match', verbose_name='Матч')),
            ],
            options={
                'verbose_name': 'Агрегат тренера',
                'verbose_name_plural': 'Агрегаты тренеров',
                'ordering': ['-match__start_time'],
                'indexes': [models.Index(fields=['coach', 'match'], name='aggregates__coach_i_d626e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('coach', 'match'), name='unique_coach_match_aggregate')],
            },
        ),
        migrations.CreateModel(
            name='MatchAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avg_entertainment', models.FloatField(default=0.0, verbose_name='Средняя зрелищность')),
                ('avg_tension', models.FloatField(default=0.0, verbose_name='Среднее напряжение')),
                ('avg_fairness', models.FloatField(default=0.0, verbose_name='Средняя справедливость')),
                ('turning_point_ratio', models.FloatField(default=0.0, verbose_name='Доля переломных моментов')),
                ('total_votes', models.IntegerField(default=0, verbose_name='Всего голосов')),
                ('drama_index', models.FloatField(default=0.0, verbose_name='Индекс драмы')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate', to='matches.match', verbose_name='Матч')),
            ],
            options={
                'verbose_name': 'Агрегат матча',
                'verbose_name_plural': 'Агрегаты матчей',
                'ordering': ['-match__start_time'],
                'indexes': [models.Index(fields=['match'], name='aggregates__match_i_c4f8b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avg_contribution', models.FloatField(default=0.0, verbose_name='Средний вклад')),
                ('avg_risk', models.FloatField(default=0.0, verbose_name='Средний риск')),
                ('avg_potential', models.FloatField(default=0.0, verbose_name='Средний потенциал')),
                ('total_votes', models.IntegerField(default=0, verbose_name='Всего голосов')),
                ('performance_score', models.FloatField(default=0.0, verbose_name='Рейтинг выступления')),
                ('risk_index', models.FloatField(default=0.0, verbose_name='Индекс риска')),
                ('maturity_score', models.FloatField(default=0.0, verbose_name='Индекс зрелости')),
                ('stability_index', models.FloatField(default=0.0, verbose_name='Индекс стабильности')),
                ('clutch_index', models.FloatField(default=0.0, verbose_name='Индекс решающих моментов')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_aggregates', to='matches.match', verbose_name='Матч')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_aggregates', to='players.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Агрегат игрока',
                'verbose_name_plural': 'Агрегаты игроков',
                'ordering': ['-performance_score'],
                'indexes': [models.Index(fields=['player', 'match'], name='aggregates__player__f6911c_idx'), models.Index(fields=['match', 'player'], name='aggregates__match_i_1102a1_idx'), models.Index(fields=['-performance_score'], name='aggregates__perform_db64c9_idx'), models.Index(fields=['match', '-performance_score'], name='aggregates__match_i_27f28a_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'match'), name='unique_player_match_aggregate')],
            },
        ),
    ]
