# Generated by Django 6.0.3 on 2026-03-18 03:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaches', '0002_coach_external_id'),
        ('matches', '0005_match_has_lineup'),
        ('players', '0002_player_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avg_entertainment', models.FloatField(default=0.0)),
                ('avg_tension', models.FloatField(default=0.0)),
                ('avg_fairness', models.FloatField(default=0.0)),
                ('turning_point_ratio', models.FloatField(default=0.0)),
                ('total_votes', models.IntegerField(default=0)),
                ('drama_index', models.FloatField(default=0.0)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregate', to='matches.match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoachMatchAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avg_tactics', models.FloatField(default=0.0)),
                ('avg_substitutions', models.FloatField(default=0.0)),
                ('avg_management', models.FloatField(default=0.0)),
                ('avg_impact', models.FloatField(default=0.0)),
                ('total_votes', models.IntegerField(default=0)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_aggregates', to='coaches.coach')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_aggregates', to='matches.match')),
            ],
            options={
                'indexes': [models.Index(fields=['coach', 'match'], name='aggregates__coach_i_d626e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('coach', 'match'), name='unique_coach_match_aggregate')],
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchAggregate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avg_contribution', models.FloatField(default=0.0)),
                ('avg_risk', models.FloatField(default=0.0)),
                ('avg_potential', models.FloatField(default=0.0)),
                ('total_votes', models.IntegerField(default=0)),
                ('performance_score', models.FloatField(default=0.0)),
                ('risk_index', models.FloatField(default=0.0)),
                ('maturity_score', models.FloatField(default=0.0)),
                ('stability_index', models.FloatField(default=0.0)),
                ('clutch_index', models.FloatField(default=0.0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_aggregates', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_aggregates', to='players.player')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'match'], name='aggregates__player__f6911c_idx'), models.Index(fields=['match', 'player'], name='aggregates__match_i_1102a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'match'), name='unique_player_match_aggregate')],
            },
        ),
    ]
