# Generated by Django 6.0.3 on 2026-03-18 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0002_add_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='playermatchaggregate',
            name='aggregates_player__22222_idx',
        ),
        migrations.RemoveIndex(
            model_name='playermatchaggregate',
            name='aggregates_match_p_33333_idx',
        ),
    ]
