# Generated by Django 6.0.3 on 2026-03-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0003_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='playermatchaggregate',
            name='aggregates_player__22222_idx',
        ),
        migrations.RemoveIndex(
            model_name='playermatchaggregate',
            name='aggregates_match_p_33333_idx',
        ),
        migrations.RenameIndex(
            model_name='matchaggregate',
            new_name='aggregates__match_i_c4f8b8_idx',
            old_name='agg_match_idx',
        ),
        migrations.RenameIndex(
            model_name='playermatchaggregate',
            new_name='aggregates__perform_db64c9_idx',
            old_name='agg_player_perf_idx',
        ),
        migrations.RenameIndex(
            model_name='playermatchaggregate',
            new_name='aggregates__match_i_27f28a_idx',
            old_name='agg_match_perf_idx',
        ),
    ]
