# Generated by Django 6.0.3 on 2026-08-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0003_team_referee_aggregates_and_coach_segments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='refereematchaggregate',
            new_name='aggregates__referee_6032b8_idx',
            old_name='aggregates__referee_9c3e5a_idx',
        ),
        migrations.RenameIndex(
            model_name='refereematchaggregate',
            new_name='aggregates__perform_3624c8_idx',
            old_name='aggregates__perform_a1d3c2_idx',
        ),
        migrations.RenameIndex(
            model_name='teammatchaggregate',
            new_name='aggregates__team_id_fd2954_idx',
            old_name='aggregates__team_id_9f6f4c_idx',
        ),
        migrations.RenameIndex(
            model_name='teammatchaggregate',
            new_name='aggregates__perform_007013_idx',
            old_name='aggregates__perform_5c1a2b_idx',
        ),
    ]
