# Generated by Django 6.0.3 on 2026-03-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0004_remove_playermatchaggregate_aggregates_player__22222_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchaggregate',
            name='clutch_index',
            field=models.FloatField(default=0.0, verbose_name='Индекс решающих моментов'),
        ),
        migrations.AlterField(
            model_name='playermatchaggregate',
            name='maturity_score',
            field=models.FloatField(default=0.0, verbose_name='Индекс зрелости'),
        ),
        migrations.AlterField(
            model_name='playermatchaggregate',
            name='performance_score',
            field=models.FloatField(default=0.0, verbose_name='Оценка выступления'),
        ),
        migrations.AlterField(
            model_name='playermatchaggregate',
            name='risk_index',
            field=models.FloatField(default=0.0, verbose_name='Индекс риска'),
        ),
        migrations.AlterField(
            model_name='playermatchaggregate',
            name='stability_index',
            field=models.FloatField(default=0.0, verbose_name='Индекс стабильности'),
        ),
    ]
