# Generated by Django 6.0.8 on 2026-09-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregates', '0009_alter_ratingcorrection_suppressed_until_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchaggregate',
            name='turning_points',
            field=models.JSONField(blank=True, default=list, verbose_name='Переломные моменты'),
        ),
    ]
