# dashboard/urls.py
from django.urls import path

from . import views, views_2fa

app_name = "dashboard"

urlpatterns = [
    path("", views.overview, name="overview"),
    path("traffic/", views.traffic, name="traffic"),
    path("matches/", views.matches_list, name="matches_list"),
    path("matches/<uuid:match_id>/", views.match_detail, name="match_detail"),
    path("matches/<uuid:match_id>/recalc/", views.match_trigger_recalc, name="match_trigger_recalc"),
    path("settings/", views.platform_settings, name="platform_settings"),
    path("settings/create/", views.platform_settings_create, name="platform_settings_create"),
    path("settings/<str:key>/update/", views.platform_settings_update, name="platform_settings_update"),
    path("settings/<str:key>/delete/", views.platform_settings_delete, name="platform_settings_delete"),
    path("users/", views.users_list, name="users_list"),
    path("users/<uuid:user_id>/", views.user_detail, name="user_detail"),
    path("users/<uuid:user_id>/toggle-ban/", views.user_toggle_ban, name="user_toggle_ban"),
    path("users/<uuid:user_id>/reset-trust/", views.user_reset_trust_score, name="user_reset_trust_score"),
    path("system-status/", views.system_status, name="system_status"),
    path("evaluations/", views.evaluation_sessions_list, name="evaluation_sessions_list"),
    path("evaluations/<uuid:session_id>/", views.evaluation_session_detail, name="evaluation_session_detail"),
    path("evaluations/<uuid:session_id>/delete/", views.evaluation_session_delete, name="evaluation_session_delete"),
    path("partners/", views.partners_list, name="partners_list"),
    path("partners/create/", views.partner_create, name="partner_create"),
    path("partners/<uuid:partner_id>/", views.partner_detail, name="partner_detail"),
    path("partners/<uuid:partner_id>/delete/", views.partner_delete, name="partner_delete"),
    path("banners/", views.banners_list, name="banners_list"),
    path("banners/create/", views.banner_create, name="banner_create"),
    path("banners/<uuid:banner_id>/", views.banner_detail, name="banner_detail"),
    path("banners/<uuid:banner_id>/delete/", views.banner_delete, name="banner_delete"),
    path("access/", views.access_roles_list, name="access_roles_list"),
    path("access/<uuid:user_id>/", views.access_roles_detail, name="access_roles_detail"),
    path("data-health/", views.data_health, name="data_health"),
    path("data-health/partial/", views.data_health_partial, name="data_health_partial"),
    # Не <uuid:...> — сюда приходят и старые числовые id матчей.
    path("data-health/matches/<str:match_id>/resync/", views.data_health_resync_match, name="data_health_resync_match"),
    path("ads/", views.ads, name="ads"),
    path("ads/stats/partial/", views.ads_stats_partial, name="ads_stats_partial"),
    path("antifraud/", views.antifraud, name="antifraud"),
    path("antifraud/export/", views.antifraud_export_csv, name="antifraud_export_csv"),
    path("antifraud/flags/<uuid:flag_id>/action/", views.antifraud_flag_action, name="antifraud_flag_action"),
    path("data-trust/", views.data_trust, name="data_trust"),
    path("data-trust/reports/<uuid:submission_id>/resolve/", views.data_trust_resolve_report, name="data_trust_resolve_report"),
    path("data-trust/discrepancies/<uuid:discrepancy_id>/review/", views.data_trust_review_discrepancy, name="data_trust_review_discrepancy"),
    path("parser/", views.parser_tools_view, name="parser_tools"),
    path("parser/tasks/partial/", views.parser_tasks_partial, name="parser_tasks_partial"),
    path("parser/trigger/", views.parser_trigger_task, name="parser_trigger_task"),
    path("parser/sportmonks-health-check/", views.parser_sportmonks_health_check, name="parser_sportmonks_health_check"),
    path("parser/sportmonks-sync-toggle/", views.sportmonks_sync_toggle, name="sportmonks_sync_toggle"),
    path("parser/tasks/<str:task_id>/revoke/", views.parser_revoke_task, name="parser_revoke_task"),
    path("scripts/", views.scripts_view, name="scripts"),
    path("scripts/runs/partial/", views.scripts_runs_partial, name="scripts_runs_partial"),
    path("scripts/trigger/", views.scripts_trigger, name="scripts_trigger"),
    path("scripts/runs/<uuid:run_id>/revoke/", views.scripts_revoke_run, name="scripts_revoke_run"),
    path("names-review/", views.names_review, name="names_review"),
    path("names-review/partial/", views.names_review_partial, name="names_review_partial"),
    path("names-review/bulk-confirm-matches/", views.names_review_bulk_confirm_matches, name="names_review_bulk_confirm_matches"),
    path("names-review/<uuid:suggestion_id>/action/", views.names_review_action, name="names_review_action"),
    # Очередь «Дубли игроков».
    path("duplicate-players/", views.duplicate_players_review, name="duplicate_players_review"),
    path("duplicate-players/<uuid:flag_id>/merge/", views.duplicate_players_merge, name="duplicate_players_merge"),
    path("duplicate-players/<uuid:flag_id>/dismiss/", views.duplicate_players_dismiss, name="duplicate_players_dismiss"),
    path("audit/", views.audit_log, name="audit_log"),
    path("announcements/", views.announcements, name="announcements"),
    # 2FA — пути без OTP-проверки.
    path("security/2fa/setup/", views_2fa.two_factor_setup, name="two_factor_setup"),
    path("security/2fa/backup-codes/", views_2fa.two_factor_backup_codes, name="two_factor_backup_codes"),
    path("security/2fa/verify/", views_2fa.two_factor_challenge, name="two_factor_challenge"),
]
