# Generated by Django 6.0.3 on 2026-03-31 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='Страна')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
            ],
            options={
                'verbose_name': 'Судья',
                'verbose_name_plural': 'Судьи',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
