# Generated by Django 6.0.8 on 2026-09-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0004_referee_name_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='photo_url',
            field=models.URLField(blank=True, default='', verbose_name='URL фото (Sportmonks)'),
        ),
    ]
