# Generated by Django 6.0.3 on 2026-08-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffactionlog',
            name='action',
            field=models.CharField(choices=[('antifraud_flag_confirmed', 'Флаг подтверждён'), ('antifraud_flag_dismissed', 'Флаг отклонён'), ('match_resync', 'Ручной ресинк матча'), ('celery_task_triggered', 'Запуск celery-задачи вручную'), ('raw_kff_lookup', 'Просмотр сырого ответа KFF API'), ('celery_task_revoked', 'Отзыв/остановка celery-задачи'), ('kff_health_check', 'Проверка доступности KFF API')], db_index=True, max_length=50, verbose_name='Действие'),
        ),
    ]
