# Generated by Django 6.0.8 on 2026-09-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_name_suggestion_audit_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementcommandrun',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
