# Generated by Django 6.0.8 on 2026-10-02 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0022_admin_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('levels', models.JSONField(blank=True, default=dict, verbose_name='Уровни по разделам')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role', to='auth.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Роль сотрудника',
                'verbose_name_plural': 'Роли сотрудников',
            },
        ),
    ]
