# Generated by Django 6.0.8 on 2026-10-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_audit_service_restart'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementcommandrun',
            name='alive_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний признак жизни'),
        ),
    ]
