# Generated by Django 6.0.8 on 2026-09-28 02:46

import django.db.models.deletion
import engagement.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0015_alter_match_manual_override_help'),
        ('players', '0013_player_photo_url'),
        ('seasons', '0002_season_sportmonks_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current', models.PositiveIntegerField(default=0, verbose_name='Текущая серия')),
                ('best', models.PositiveIntegerField(default=0, verbose_name='Лучшая серия')),
                ('last_active_date', models.DateField(blank=True, null=True, verbose_name='Последний активный день')),
                ('freezes', models.PositiveSmallIntegerField(default=0, verbose_name='Заморозки')),
                ('freezes_used', models.PositiveIntegerField(default=0, verbose_name='Использовано заморозок')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Серия дней',
                'verbose_name_plural': 'Серии дней',
            },
        ),
        migrations.CreateModel(
            name='ExpertTake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_title', models.CharField(default='Редакция DOPX', max_length=80, verbose_name='Подпись автора')),
                ('text', models.TextField(max_length=600, verbose_name='Мнение')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('key_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='players.player', verbose_name='Ключевой игрок')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_takes', to='matches.match')),
            ],
            options={
                'verbose_name': 'Мнение эксперта',
                'verbose_name_plural': 'Мнения экспертов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FriendLeague',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('invite_code', models.CharField(default=engagement.models._invite_code, max_length=12, unique=True, verbose_name='Код приглашения')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_friend_leagues', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_leagues', to='seasons.season')),
            ],
            options={
                'verbose_name': 'Лига прогнозистов',
                'verbose_name_plural': 'Лиги прогнозистов',
            },
        ),
        migrations.CreateModel(
            name='FriendLeagueMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='engagement.friendleague')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_league_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник лиги',
                'verbose_name_plural': 'Участники лиг',
            },
        ),
        migrations.AddField(
            model_name='friendleague',
            name='members',
            field=models.ManyToManyField(related_name='friend_leagues', through='engagement.FriendLeagueMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('link', 'Ссылка-приглашение'), ('challenge', 'Вызов на прогноз'), ('league', 'Лига прогнозистов')], default='link', max_length=20, verbose_name='Источник')),
                ('rewarded_at', models.DateTimeField(blank=True, null=True, verbose_name='Награда выдана')),
                ('invited', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Приглашение',
                'verbose_name_plural': 'Приглашения',
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(default=engagement.models._invite_code, max_length=12, unique=True, verbose_name='Код')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Код приглашения',
                'verbose_name_plural': 'Коды приглашений',
            },
        ),
        migrations.CreateModel(
            name='SeasonPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('xp', models.PositiveIntegerField(default=0, verbose_name='XP сезона')),
                ('claimed_levels', models.JSONField(blank=True, default=list, verbose_name='Выданные награды (уровни)')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='seasons.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сезонный пропуск',
                'verbose_name_plural': 'Сезонные пропуски',
            },
        ),
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='День')),
                ('key', models.CharField(max_length=40, verbose_name='Задание')),
                ('target', models.PositiveSmallIntegerField(default=1, verbose_name='Цель')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='Прогресс')),
                ('xp_reward', models.PositiveSmallIntegerField(default=10, verbose_name='Награда XP')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задание дня',
                'verbose_name_plural': 'Задания дня',
                'indexes': [models.Index(fields=['user', 'date'], name='engagement__user_id_36653f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date', 'key'), name='unique_daily_quest')],
            },
        ),
        migrations.AddConstraint(
            model_name='friendleaguemember',
            constraint=models.UniqueConstraint(fields=('league', 'user'), name='unique_friend_league_member'),
        ),
        migrations.AddIndex(
            model_name='seasonpass',
            index=models.Index(fields=['season', '-xp'], name='engagement__season__819ae5_idx'),
        ),
        migrations.AddConstraint(
            model_name='seasonpass',
            constraint=models.UniqueConstraint(fields=('user', 'season'), name='unique_season_pass'),
        ),
    ]
