# Generated by Django 6.0.8 on 2026-09-28 03:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        ('events', '0006_matchevent_sportmonks_id'),
        ('matches', '0015_alter_match_manual_override_help'),
        ('players', '0013_player_photo_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('episode', 'Спорный момент'), ('duel', 'Дуэль тура')], max_length=10, verbose_name='Тип')),
                ('question', models.CharField(max_length=160, verbose_name='Вопрос')),
                ('context', models.CharField(blank=True, max_length=255, verbose_name='Контекст')),
                ('option_a', models.CharField(max_length=80, verbose_name='Вариант A')),
                ('option_b', models.CharField(max_length=80, verbose_name='Вариант B')),
                ('detail_a', models.CharField(blank=True, max_length=120)),
                ('detail_b', models.CharField(blank=True, max_length=120)),
                ('score', models.FloatField(default=0.0, verbose_name='Индекс спорности')),
                ('closes_at', models.DateTimeField(verbose_name='Закрывается')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.matchevent')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_polls', to='matches.match')),
                ('player_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='players.player')),
                ('player_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='players.player')),
            ],
            options={
                'verbose_name': 'Опрос недели',
                'verbose_name_plural': 'Опросы недели',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.CharField(choices=[('a', 'A'), ('b', 'B')], max_length=1)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='engagement.dailypoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('poll', 'user'), name='unique_poll_vote')],
            },
        ),
    ]
