# Generated by Django 6.0.8 on 2026-09-29 03:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_daily_polls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('title', models.CharField(blank=True, help_text='Коротко: «экс-игрок сборной Казахстана», «тренер UEFA A»', max_length=120, verbose_name='Кто это')),
                ('photo', models.ImageField(blank=True, upload_to='experts/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Эксперт',
                'verbose_name_plural': 'Эксперты',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='experttake',
            options={'ordering': ['created_at'], 'verbose_name': 'Мнение эксперта', 'verbose_name_plural': 'Мнения экспертов'},
        ),
        migrations.AddField(
            model_name='experttake',
            name='headline',
            field=models.CharField(blank=True, help_text='Одна фраза крупно над текстом', max_length=140, verbose_name='Главная мысль'),
        ),
        migrations.AlterField(
            model_name='experttake',
            name='text',
            field=models.TextField(max_length=3000, verbose_name='Мнение'),
        ),
        migrations.AddField(
            model_name='experttake',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takes', to='engagement.expert', verbose_name='Эксперт'),
        ),
    ]
