# Generated by Django 6.0.8 on 2026-09-29 03:26

import django.db.models.deletion
import engagement.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_experts'),
        ('matches', '0015_alter_match_manual_override_help'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=engagement.models._invite_token, editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('max_takes', models.PositiveSmallIntegerField(default=1, verbose_name='Сколько мнений можно написать')),
                ('auto_publish', models.BooleanField(default=False, verbose_name='Публиковать без проверки')),
                ('note', models.CharField(blank=True, max_length=120, verbose_name='Заметка для себя')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='engagement.expert', verbose_name='Эксперт')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_invites', to='matches.match', verbose_name='Матч')),
            ],
            options={
                'verbose_name': 'Ссылка для эксперта',
                'verbose_name_plural': 'Ссылки для экспертов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='experttake',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takes', to='engagement.expertinvite', verbose_name='Прислано по ссылке'),
        ),
    ]
