# Generated by Django 6.0.8 on 2026-10-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_expert_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='experttake',
            name='review_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Комментарий редакции'),
        ),
    ]
