# Generated by Django 6.0.8 on 2026-10-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_experttake_review_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonpass',
            options={'verbose_name': 'Абонемент', 'verbose_name_plural': 'Абонементы'},
        ),
    ]
