# Generated by Django 6.0.8 on 2026-10-05 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0006_season_pass_abonement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquest',
            name='param',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Параметр'),
        ),
        migrations.CreateModel(
            name='QuestCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=40, verbose_name='Задание')),
                ('ref', models.CharField(max_length=64, verbose_name='Объект')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменено')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='engagement.dailyquest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Засчитанное действие',
                'verbose_name_plural': 'Засчитанные действия',
                'constraints': [models.UniqueConstraint(fields=('user', 'key', 'ref'), name='unique_quest_credit')],
            },
        ),
    ]
