# Generated by Django 6.0.3 on 2026-08-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season_squad', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='seasonbestxislot',
            new_name='season_squa_content_81a593_idx',
            old_name='season_squ_content_e0f8c1_idx',
        ),
        migrations.RenameIndex(
            model_name='seasonpositionranking',
            new_name='season_squa_best_xi_1791c5_idx',
            old_name='season_squ_best_xi_f3f6f9_idx',
        ),
        migrations.RenameIndex(
            model_name='seasonpositionranking',
            new_name='season_squa_best_xi_29f086_idx',
            old_name='season_squ_best_xi_6c2f7f_idx',
        ),
        migrations.RenameIndex(
            model_name='seasonpositionranking',
            new_name='season_squa_content_e126ee_idx',
            old_name='season_squ_content_9b3f2a_idx',
        ),
    ]
