# Generated by Django 6.0.3 on 2026-08-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season_squad', '0002_rename_season_squ_content_e0f8c1_idx_season_squa_content_81a593_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonbestxi',
            options={'verbose_name': 'Сборная DOPX', 'verbose_name_plural': 'Сборные DOPX'},
        ),
    ]
