# Generated by Django 6.0.8 on 2026-10-02 05:48

import adminbot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('telegram_name', models.CharField(blank=True, max_length=120, verbose_name='Имя в Telegram')),
                ('notify', models.BooleanField(default=True, verbose_name='Присылать уведомления')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Привязан')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Последнее действие')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_link', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Привязка к боту',
                'verbose_name_plural': 'Привязки к боту',
            },
        ),
        migrations.CreateModel(
            name='BotLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=adminbot.models._code, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
