# Generated by Django 6.0.8 on 2026-10-02 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0001_admin_bot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modes', models.JSONField(blank=True, default=dict)),
                ('quiet_hours', models.BooleanField(default=True, verbose_name='Не публиковать ночью (23:00–09:00)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='botlink',
            name='duty_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Очередь дежурства'),
        ),
        migrations.AddField(
            model_name='botlink',
            name='topics',
            field=models.JSONField(blank=True, null=True, verbose_name='Темы уведомлений'),
        ),
        migrations.CreateModel(
            name='ChannelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('preview', 'Анонс тура'), ('result', 'Финал матча'), ('ratings', 'Оценки болельщиков'), ('round', 'Итоги тура'), ('expert', 'Мнение эксперта'), ('changes', 'Переносы и отмены'), ('manual', 'Свой пост')], default='manual', max_length=20, verbose_name='Тип')),
                ('key', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('text', models.TextField(max_length=4000, verbose_name='Текст')),
                ('image', models.CharField(blank=True, max_length=300, verbose_name='Картинка (путь в хранилище)')),
                ('tg_file_id', models.CharField(blank=True, max_length=200)),
                ('buttons', models.JSONField(blank=True, default=list, verbose_name='Кнопки-ссылки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирован'), ('published', 'Опубликован'), ('failed', 'Ошибка'), ('cancelled', 'Удалён')], db_index=True, default='draft', max_length=12, verbose_name='Статус')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовать в')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликован')),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пост в канал',
                'verbose_name_plural': 'Посты в канал',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('rows', models.JSONField(blank=True, default=list)),
                ('section', models.CharField(default='system_status', max_length=40)),
                ('perm', models.CharField(blank=True, max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('next_escalation_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
                'ordering': ['-created_at'],
            },
        ),
    ]
