# Generated by Django 6.0.8 on 2026-10-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbot', '0002_channel_incidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpost',
            name='by_ai',
            field=models.BooleanField(default=False, verbose_name='Текст написал Claude'),
        ),
        migrations.AddField(
            model_name='channelpost',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='Ещё картинки (альбом)'),
        ),
        migrations.AddField(
            model_name='channelpost',
            name='poll',
            field=models.JSONField(blank=True, null=True, verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='channelpost',
            name='kind',
            field=models.CharField(choices=[('preview', 'Превью тура'), ('result', 'Финал матча'), ('ratings', 'Разбор матча'), ('round', 'Итоги тура'), ('poll', 'Опрос'), ('controversy', 'Спорный момент недели'), ('number', 'Цифра недели'), ('expert', 'Мнение эксперта'), ('changes', 'Переносы и отмены'), ('manual', 'Свой пост')], default='manual', max_length=20, verbose_name='Тип'),
        ),
    ]
