# Generated by Django 6.0.3 on 2026-03-31 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('home', 'Домашние'), ('away', 'Гостевые')], max_length=10, verbose_name='Сторона')),
                ('formation', models.CharField(blank=True, max_length=20, verbose_name='Формация')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='matches.match', verbose_name='Матч')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Состав на матч',
                'verbose_name_plural': 'Составы на матчи',
            },
        ),
        migrations.CreateModel(
            name='MatchLineupPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_starting', models.BooleanField(default=True, verbose_name='В старте')),
                ('position', models.CharField(blank=True, max_length=20, verbose_name='Позиция')),
                ('shirt_number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('minute_in', models.IntegerField(blank=True, null=True, verbose_name='Минута выхода')),
                ('minute_out', models.IntegerField(blank=True, null=True, verbose_name='Минута замены')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='lineups.matchlineup', verbose_name='Состав')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Игрок в составе',
                'verbose_name_plural': 'Игроки в составе',
                'ordering': ['is_starting', 'shirt_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='matchlineup',
            constraint=models.UniqueConstraint(fields=('match', 'team'), name='unique_match_team_lineup'),
        ),
        migrations.AddIndex(
            model_name='matchlineupplayer',
            index=models.Index(fields=['lineup', 'is_starting'], name='lineups_mat_lineup__24f020_idx'),
        ),
        migrations.AddIndex(
            model_name='matchlineupplayer',
            index=models.Index(fields=['player', 'lineup'], name='lineups_mat_player__f76e27_idx'),
        ),
    ]
