# Generated by Django 6.0.3 on 2026-03-12 05:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0003_match_stadium'),
        ('players', '0002_player_external_id'),
        ('teams', '0002_team_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLineup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(choices=[('home', 'Home'), ('away', 'Away')], max_length=10)),
                ('formation', models.CharField(blank=True, max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchLineupPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_starting', models.BooleanField(default=True)),
                ('position', models.CharField(blank=True, max_length=20)),
                ('shirt_number', models.IntegerField(blank=True, null=True)),
                ('minute_in', models.IntegerField(blank=True, null=True)),
                ('minute_out', models.IntegerField(blank=True, null=True)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='lineups.matchlineup')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
