# Generated by Django 6.0.3 on 2026-08-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0003_matchlineupplayer_field_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchlineupplayer',
            name='field_position',
            field=models.CharField(blank=True, help_text="Сырое значение 'field_position' из ответа KFF (/games/<id>/lineup) — C/L/R/LC/RC, колонка формации (не путать с амплуа в поле 'Позиция' выше). Найдено 2026-08-23: это поле присутствовало в ответе API у КАЖДОГО игрока состава всё это время, но не импортировалось — именно оно даёт сторону поля (левый/правый/центр), которой не хватало для точного распределения слотов формации в season_squad/round_squad (см. players/positions.py).", max_length=5, verbose_name='Сторона на поле'),
        ),
    ]
