# Generated by Django 6.0.3 on 2026-03-31 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='leagues/', verbose_name='Логотип')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
            ],
            options={
                'verbose_name': 'Лига',
                'verbose_name_plural': 'Лиги',
                'ordering': ['name'],
            },
        ),
    ]
