# Generated by Django 6.0.3 on 2026-03-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_league_external_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'ordering': ['name'], 'verbose_name': 'Лига', 'verbose_name_plural': 'Лиги'},
        ),
        migrations.AlterField(
            model_name='league',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='league',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='league',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='leagues/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
