# Generated by Django 6.0.3 on 2026-03-31 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Позиция')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='teams.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['team', 'is_active'], name='players_pla_team_id_1a80c1_idx'), models.Index(fields=['last_name', 'first_name'], name='players_pla_last_na_1786cf_idx')],
            },
        ),
    ]
