# Generated by Django 6.0.8 on 2026-09-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_player_last_match_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='player',
            name='players_pla_team_id_1a80c1_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='players_pla_last_na_1786cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='playersidelined',
            name='players_pla_player__f7d1d1_idx',
        ),
    ]
