# Generated by Django 6.0.8 on 2026-09-22 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_player_name_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialDuplicatePlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_label', models.CharField(blank=True, max_length=200, verbose_name='Команда (снэпшот)')),
                ('reviewed', models.BooleanField(db_index=True, default=False, verbose_name='Разобрано')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда разобрано')),
                ('note', models.TextField(blank=True, help_text='Например: "подтверждено, слил вручную" или "ложное срабатывание — разные люди".', verbose_name='Заметка')),
                ('existing_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='players.player', verbose_name='Уже существующий игрок')),
                ('new_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='players.player', verbose_name='Новая запись (возможно, тот же человек)')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто разобрал')),
            ],
            options={
                'verbose_name': 'Возможный дубль игрока',
                'verbose_name_plural': 'Возможные дубли игроков',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('existing_player', 'new_player'), name='potential_dup_player_unique_pair')],
            },
        ),
    ]
