# Generated by Django 6.0.8 on 2026-09-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_alter_player_roster_absence_streak_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_url',
            field=models.URLField(blank=True, default='', verbose_name='URL фото (Sportmonks)'),
        ),
    ]
