# Generated by Django 6.0.8 on 2026-10-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_player_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='squad_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждён в составе'),
        ),
    ]
