# Generated by Django 6.0.8 on 2026-10-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0014_current_squad'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersidelined',
            name='games_missed',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Пропущено матчей'),
        ),
        migrations.AddField(
            model_name='playersidelined',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Причина'),
        ),
    ]
