# Generated by Django 6.0.8 on 2026-10-10 08:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_sidelined_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSportmonksAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sportmonks_id', models.CharField(max_length=100, unique=True, verbose_name='Sportmonks ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sportmonks_aliases', to='players.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Дополнительный id игрока у поставщика',
                'verbose_name_plural': 'Дополнительные id игроков у поставщика',
            },
        ),
    ]
