# Generated by Django 6.0.3 on 2026-03-31 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_email', models.EmailField(blank=True, help_text='Заполняется если пользователь не авторизован', max_length=254, verbose_name='Email гостя')),
                ('category', models.CharField(choices=[('general', 'Общий вопрос'), ('bug', 'Сообщение об ошибке'), ('feature', 'Предложение функции'), ('evaluation', 'Проблема с оценкой матча'), ('account', 'Вопрос по аккаунту'), ('other', 'Другое')], default='general', max_length=30, verbose_name='Категория')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('attachment', models.FileField(blank=True, help_text='Скриншот или документ (макс. 5MB)', null=True, upload_to='contact_attachments/', verbose_name='Вложение')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_response', models.TextField(blank=True, help_text='Внутренний ответ для истории', verbose_name='Ответ админа')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='notificatio_status_2c1cfa_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_a9c8fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('match_finished', 'Матч завершён'), ('voting_open', 'Голосование открыто'), ('voting_closing', 'Голосование закрывается'), ('aggregate_updated', 'Агрегаты обновлены'), ('top_performance', 'Вы в топ-3 матча'), ('verification_required', 'Требуется верификация'), ('new_badge', 'Новое достижение'), ('level_up', 'Новый уровень'), ('system', 'Системное')], default='system', max_length=30, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='URL действия')),
                ('related_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='matches.match', verbose_name='Матч')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
