# Generated by Django 6.0.3 on 2026-04-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactsubmission',
            name='notificatio_status_2c1cfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactsubmission',
            name='notificatio_user_id_a9c8fb_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Приветственное письмо'), ('match_finished', 'Матч завершён / Голосование открыто'), ('voting_closing', 'Напоминание о закрытии голосования'), ('new_badge', 'Новое достижение'), ('level_up', 'Повышение уровня'), ('system', 'Системное уведомление')], default='system', max_length=30, verbose_name='Тип уведомления'),
        ),
    ]
