# Generated by Django 6.0.3 on 2026-03-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='admin_response',
            field=models.TextField(blank=True, help_text='Внутренний ответ для истории', verbose_name='Ответ админа'),
        ),
    ]
