# Generated by Django 6.0.3 on 2026-03-31 06:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_email', models.EmailField(blank=True, help_text='Заполняется если отправитель — гость', max_length=254, verbose_name='Email отправителя')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('attachment', models.FileField(blank=True, help_text='Опционально (макс. 5MB)', null=True, upload_to='ticket_messages/', verbose_name='Вложение')),
                ('is_admin_message', models.BooleanField(default=False, help_text='Отметьте если это ответ от поддержки', verbose_name='Ответ админа')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.contactsubmission', verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket', '-created_at'], name='notificatio_ticket__4380dd_idx'), models.Index(fields=['is_admin_message', '-created_at'], name='notificatio_is_admi_5b95ba_idx')],
            },
        ),
    ]
