# Generated by Django 6.0.3 on 2026-08-14 03:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_matches_mat_status_2e1034_idx'),
        ('notifications', '0002_remove_contactsubmission_notificatio_status_2c1cfa_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email отправлен'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Приветственное письмо'), ('match_finished', 'Матч завершён / Голосование открыто'), ('voting_open', 'Голосование открыто'), ('voting_closing', 'Напоминание о закрытии голосования'), ('new_badge', 'Новое достижение'), ('level_up', 'Повышение уровня'), ('aggregate_updated', 'Обновление рейтинга'), ('top_performance', 'Топ-выступление'), ('verification_required', 'Требуется подтверждение email'), ('system', 'Системное уведомление')], default='system', max_length=30, verbose_name='Тип уведомления'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['email_sent_at'], name='notificatio_email_s_2117c5_idx'),
        ),
    ]
