# Generated by Django 6.0.3 on 2026-03-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_ticketmessage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactsubmission',
            name='notificatio_status_2c1cfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactsubmission',
            name='notificatio_user_id_a9c8fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactsubmission',
            name='notificatio_categor_58d542_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketmessage',
            name='notificatio_ticket__4380dd_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticketmessage',
            name='notificatio_is_admi_5b95ba_idx',
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Прочитано'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='message_type',
            field=models.CharField(choices=[('user', 'От пользователя'), ('admin', 'От админа'), ('system', 'Системное')], default='user', max_length=10, verbose_name='Тип сообщения'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('waiting_user', 'Ожидает ответа пользователя'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='ticket_messages/', verbose_name='Вложение'),
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='admin_response',
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='contactsubmission',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='is_admin_message',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='is_sent',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='sent_at',
        ),
    ]
