# Generated by Django 6.0.3 on 2026-03-31 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_remove_contactsubmission_notificatio_status_2c1cfa_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='admin_response',
            field=models.TextField(blank=True, help_text='Внутренний ответ для истории', verbose_name='Ответ админа'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['status', '-created_at'], name='notificatio_status_2c1cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_a9c8fb_idx'),
        ),
    ]
