# Generated by Django 6.0.3 on 2026-03-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_contactsubmission_admin_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmessage',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='message_type',
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='is_admin_message',
            field=models.BooleanField(default=False, help_text='Отметьте если это ответ от поддержки', verbose_name='Ответ админа'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='sender_email',
            field=models.EmailField(blank=True, help_text='Заполняется если отправитель — гость', max_length=254, verbose_name='Email отправителя'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено в'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Опционально (макс. 5MB)', null=True, upload_to='ticket_messages/', verbose_name='Вложение'),
        ),
    ]
