# Generated by Django 6.0.3 on 2026-03-31 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_remove_ticketmessage_is_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', '-created_at'], name='notificatio_ticket__4380dd_idx'),
        ),
    ]
