# Generated by Django 6.0.3 on 2026-08-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('welcome', 'Приветственное письмо'), ('match_finished', 'Матч завершён / Голосование открыто'), ('voting_open', 'Голосование открыто'), ('voting_closing', 'Напоминание о закрытии голосования'), ('new_badge', 'Новое достижение'), ('level_up', 'Повышение уровня'), ('aggregate_updated', 'Обновление рейтинга'), ('top_performance', 'Топ-выступление'), ('verification_required', 'Требуется подтверждение email'), ('system', 'Системное уведомление'), ('prediction_closing', 'Скоро закроется приём прогнозов'), ('weekly_digest', 'Персональная сводка недели'), ('prediction_result', 'Прогноз vs результат матча'), ('round_results', 'Итоги «DOPX Лучшие тура»')], default='system', max_length=30, verbose_name='Тип уведомления'),
        ),
    ]
