# Generated by Django 6.0.3 on 2026-03-31 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_ticketmessage_notificatio_ticket__4380dd_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='admin_response',
        ),
        migrations.RemoveField(
            model_name='ticketmessage',
            name='is_admin_message',
        ),
        migrations.AddField(
            model_name='notification',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.contactsubmission', verbose_name='Обращение'),
        ),
        migrations.AddField(
            model_name='ticketmessage',
            name='message_type',
            field=models.CharField(choices=[('user', 'От пользователя'), ('admin', 'От админа'), ('system', 'Системное')], default='user', max_length=10, verbose_name='Тип сообщения'),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В работе'), ('waiting_user', 'Ожидает ответа пользователя'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('match_finished', 'Матч завершён'), ('voting_open', 'Голосование открыто'), ('voting_closing', 'Голосование закрывается'), ('aggregate_updated', 'Агрегаты обновлены'), ('top_performance', 'Вы в топ-3 матча'), ('verification_required', 'Требуется верификация'), ('new_badge', 'Новое достижение'), ('level_up', 'Новый уровень'), ('system', 'Системное'), ('ticket_created', 'Создано обращение'), ('ticket_reply', 'Ответ поддержки'), ('ticket_status_changed', 'Статус обращения изменён')], default='system', max_length=30, verbose_name='Тип уведомления'),
        ),
    ]
