# Generated by Django 6.0.3 on 2026-03-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_remove_contactsubmission_admin_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsubmission',
            name='message',
        ),
    ]
